import { z } from 'zod';

export const ItemSchema = z.object({
  id: z.string(),
  imageName: z.string(),
  internalId: z.string(),
  name: z.string(),
  description: z.string(),
  rarity: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  maxStackCount: z.number(),
  weight: z.number(),
  price: z.number(),
  restoreSatiety: z.number(),
  restoreConcentration: z.number(),
  restoreSanity: z.number(),
  restoreHealth: z.number(),
  durability: z.number(),
  magazineSize: z.number(),
  physicalAttackValue: z.number(),
  hpValue: z.number(),
  physicalDefenseValue: z.number(),
  shieldValue: z.number(),
  magicAttackValue: z.number(),
  magicDefenseValue: z.number(),
  corruptionFactor: z.number(),
  typeA: z.string(),
  typeB: z.string(),
});
