import { z } from 'zod';

const SkillSchema = z.object({
  level: z.number(),
  bIsWeaponDamage: z.boolean(),
  cameraShake: z.string(),
  category: z.string(),
  coolTime: z.number(),
  description: z.string(),
  disabledData: z.boolean(),
  effectType1: z.string(),
  effectType2: z.string(),
  effectValue1: z.number(),
  effectValue2: z.number(),
  effectValueEx1: z.number(),
  effectValueEx2: z.number(),
  element: z.string(),
  forceRagdollSize: z.string(),
  id: z.string(),
  ignoreRandomInherit: z.boolean(),
  isLeanBack: z.boolean(),
  maxRange: z.number(),
  minRange: z.number(),
  name: z.string(),
  power: z.number(),
  specialAttackRateInfos: z.array(z.object({})),
});

const DropSchema = z.object({
  id: z.string(),
  name: z.string(),
  rate: z.number(),
  min: z.number(),
  max: z.number(),
});

export const PalSchema = z.object({
  activeSkills: z.array(SkillSchema),
  aiResponse: z.string(),
  aiSightResponse: z.string(),
  battleBgm: z.string(),
  biologicalGrade: z.number(),
  captureRateCorrect: z.number(),
  combiRank: z.number(),
  craftSpeed: z.number(),
  defense: z.number(),
  description: z.string().nullable(),
  drops: z.array(DropSchema),
  edible: z.boolean(),
  elementType1: z.string(),
  elementType2: z.string().nullable(),
  enemyReceiveDamageRate: z.number(),
  expRatio: z.number(),
  foodAmount: z.number(),
  fullStomachDecreaseRate: z.number(),
  genusCategory: z.string(),
  hearingRate: z.number(),
  hp: z.number(),
  id: z.string(),
  ignoreBlowAway: z.boolean(),
  ignoreLeanBack: z.boolean(),
  internalName: z.string(),
  isBoss: z.boolean(),
  isPal: z.boolean(),
  isTowerBoss: z.boolean(),
  maleProbability: z.number(),
  maxFullStomach: z.number(),
  meleeAttack: z.number(),
  name: z.string(),
  namePrefixId: z.string(),
  nocturnal: z.boolean(),
  nooseTrap: z.boolean(),
  organization: z.string(),
  overrideNameTextId: z.string(),
  overridePartnerSkillTextId: z.string(),
  partnerSkill: z.object({
    name: z.string().nullable(),
    description: z.string().nullable(),
  }),
  passiveSkill1: z.string(),
  passiveSkill2: z.string(),
  passiveSkill3: z.string(),
  passiveSkill4: z.string(),
  predator: z.boolean(),
  price: z.number(),
  rarity: z.number(),
  rideSprintSpeed: z.number(),
  runSpeed: z.number(),
  shotAttack: z.number(),
  size: z.string(),
  slowWalkSpeed: z.number(),
  stamina: z.number(),
  support: z.number(),
  title: z.string().nullable(),
  transportSpeed: z.number(),
  tribe: z.string(),
  viewingAngle: z.number(),
  viewingDistance: z.number(),
  walkSpeed: z.number(),
  weapon: z.string(),
  weaponEquip: z.boolean(),
  workSuitabilities: z.object({
    gathering: z.number(),
    cooling: z.number(),
    lumbering: z.number(),
    kindling: z.number(),
    'generating-electricity': z.number(),
    handiwork: z.number(),
    mining: z.number(),
    farming: z.number(),
    'oil-extraction': z.number(),
    'medicine-production': z.number(),
    planting: z.number(),
    transporting: z.number(),
    watering: z.number(),
  }),
  zukanIndex: z.number(),
  zukanIndexSuffix: z.string(),
});
