import { type WORK_SUITABILITIES } from '@/constants';

export interface Pal {
  aiResponse: string;
  aiSightResponse: string;
  battleBgm?: string;
  biologicalGrade: number;
  bpClass: string;
  captureRateCorrect: number;
  combiRank: number;
  craftSpeed: number;
  defense: number;
  edible: boolean;
  elementType1: string;
  elementType2: string | null;
  enemyReceiveDamageRate: number;
  expRatio: number;
  foodAmount: number;
  fullStomachDecreaseRate: number;
  genusCategory: string;
  hearingRate: number;
  hp: number;
  id: string;
  ignoreBlowAway: boolean;
  ignoreLeanBack: boolean;
  internalName: string;
  isBoss: boolean;
  isPal: boolean;
  isTowerBoss: boolean;
  maleProbability: number;
  maxFullStomach: number;
  meleeAttack: number;
  name: string;
  namePrefixId?: string;
  nocturnal: boolean;
  nooseTrap: boolean;
  organization: string;
  overrideNameTextId?: string;
  overridePartnerSkillTextId?: string;
  passiveSkill1: string;
  passiveSkill2: string;
  passiveSkill3: string;
  passiveSkill4: string;
  predator: boolean;
  price: number;
  rarity: number;
  rideSprintSpeed: number;
  runSpeed: number;
  shotAttack: number;
  size: string;
  slowWalkSpeed: number;
  stamina: number;
  support: number;
  tagline: string;
  transportSpeed: number;
  tribe: string;
  viewingAngle: number;
  viewingDistance: number;
  walkSpeed: number;
  weapon: string;
  weaponEquip: boolean;
  workSuitabilities: Record<WorkSuitability, number>;
  zukanIndex: number;
  zukanIndexSuffix: string;
  battleBGM?: string;
  namePrefixID?: string;
  overrideNameTextID?: string;
  overridePartnerSkillTextID?: string;
}

export type WorkSuitability = (typeof WORK_SUITABILITIES)[number];
